import Sidebar from '@/components/general/nav/sidebar/SideBar';
import Header from '@/components/general/nav/Header';
import { headers } from 'next/headers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const h = await headers();
  const url = h.get('x-url') || '';

  const type = url.includes('/doctor')
    ? 'doctor'
    : url.includes('/patient')
      ? 'patient'
      : 'employee';
  return (
    <div>
      <div className="grid grid-rows-[auto_1fr]">
        <Header type={type} />
        <main className="grid grid-cols-[auto_1fr]">
          <Sidebar type={type} />
          <div className="mx-auto h-[calc(100vh-64px)] w-full max-w-7xl overflow-y-auto p-6 pb-10">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
}
